name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow write access to the repository contents

    name: Check all sites
    steps:
      - uses: actions/checkout@v2

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh

      - name: Configure Git
        run: |
          git config --global user.name 'Chavindu Nuwanpriya'
          git config --global user.email 'chavindun@gmail.com'

      - name: Push Health Check Logs
        run: |
          git add -A --force logs/
          git commit -m '[Automated] Update Health Check Logs' || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/BitLab-LK/status-page.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
